### PR TITLE
Fix nox not returning a non-zero exit code on failure

### LINKED ISSUE #54: `nox` always exits with 0, even if a test fails.
See [repro][1]. It is making my [builds][2] pass when they didn't mean to.

H/T to @will-e-p for being my OS X guinea pig.

[1]: https://gist.github.com/dhermes/1153863ddd3dfb44c2e3cf3206a0bcea
[2]: https://travis-ci.org/dhermes/bezier/jobs/277146609

### PR DESCRIPTION
**Pull request by jonparrott**
Resolves #54

### CODE REVIEW

**Comment by dhermes** [comment]
@jonparrott Didn't there used to be a summary of all the sessions at the end of the output? (I am back through `0.11.1` and don't see it.)

**Comment by jonparrott** [comment]
Yeah, @lukesneeringer what happened to that?

**Comment by lukesneeringer** [comment]
I probably broke it by accident. Give me a couple hours and I can add it back.

**Comment by jonparrott** [comment]
SG. I'm gonna go ahead and merge this and send a separate PR to restore coverage.

**Comment by dhermes** [comment]
Yeah I was just running with `nox` rather than `venv/bin/nox`, that was also a `0.18.0` regression:

```
$ venv/bin/pip install -I 'nox-automation==0.17.0' > /dev/null 2>&1 && venv/bin/nox
nox > Running session bad
nox > virtualenv ${HERE}/.nox/bad
nox > chdir ${HERE}
nox > false
nox > Command false failed with exit code 1
nox > Session bad failed. :(
nox > Running session good
nox > virtualenv ${HERE}/.nox/good
nox > chdir ${HERE}
nox > true
nox > Session good successful. :)
nox > Ran multiple sessions:
nox > * bad: failed
nox > * good: passed
$
$ venv/bin/pip install -I 'nox-automation==0.18.0' > /dev/null 2>&1 && venv/bin/nox
nox > Running session bad
nox > ${HERE}/venv/bin/python3.6 -m virtualenv ${HERE}/.nox/bad
nox > chdir ${HERE}
nox > false
nox > Command false failed with exit code 1
nox > Session bad failed.
nox > Running session good
nox > ${HERE}/venv/bin/python3.6 -m virtualenv ${HERE}/.nox/good
nox > chdir ${HERE}
nox > true
nox > Session good was successful.
```

**Pull request merged**
