### PR TITLE
Parametrize

### LINKED ISSUE #1: Parametrization
Building a bit on https://www.reddit.com/r/Python/comments/48qz7w/nox_virtualenvtest_automation_similar_to_tox_but/d0m3q4l, another way to handle parametrization is like this:
```python
@nox.parametrize('python', ['/path/to/python2.7', '/path/to/python3.5', '/path/to/pypy', ...], ids=['py27', 'py34', 'pypy', ...])
@nox.parametrize('django', ['1.9', '1.8', ...])
def session_test(session, python, django):
   ...
```

This is quite identical to [pytest parametrization](http://pytest.org/latest/parametrize.html?highlight=parametrize). 

The advantage over your initial proposal is that you can customize the display names (via `ids`).

Also, would be good to know how far and where you'd take nox. IOW, what goals does nox have? 

PS. There is no contribution guide.

### PR DESCRIPTION
**Pull request by jonparrott**
Fixes #1

/cc @ionelmc

### CODE REVIEW

**Comment by ionelmc** [comment]
Awesome stuff :D

**Comment by jonparrott** [comment]
@ionelmc before I merge, can I validate that this satisfies your use case?

**Comment by ionelmc** [comment]
It mostly does. I miss a "skip" option tho - eg: you can't run django 1.9 on python 2.6. That could be added later right?

For reference, you can "skip a parameter" in pytest: http://pytest.org/latest/skipping.html?highlight=parametrize#skip-xfail-with-parametrize

**Comment by jonparrott** [comment]
@ionelmc yeah. You're welcome to file another bug for that.

In the meantime, that one isn't hard to do within the session itself:

```python
def session_blah(session, foo):
    if foo in ('bad', 'worse'):
        print('Not running with arg {}.format(foo)
        return
```

**Pull request merged**
